name: finance
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.3.1
  google_nav_bar: ^2.2.0
  feather_icons_flutter: ^4.7.4
  cached_network_image: ^2.2.0+1
  table_calendar: ^2.2.3
  get: ^3.4.1
  timeago: ^2.0.26
  bot_toast: ^3.0.0
  geolocator: ^5.3.2+2
  flutter_map: ^0.10.1
  user_location:
    git:
      url: https://github.com/igaurab/user_location_plugin.git
  flutter_map_marker_popup: ^0.1.4
  shared_preferences: ^0.5.8
  hive_flutter: ^0.3.1
  hive: ^1.4.2

dev_dependencies:
  hive_generator: ^0.7.1
  build_runner: ^1.10.0

flutter:
  uses-material-design: true

fonts:
  - family: GoogleSans-Regular     
    fonts:
    - asset: fonts/ProductSans-Regular.ttf
   
  - family: GoogleSans-Bold     
    fonts:
    - asset: fonts/ProductSans-Bold.ttf
  - family: GoogleSans-Italic
    fonts:
    - asset: fonts/ProductSans-Italic.ttf
  - family: GoogleSans-Bold-Italic
    fonts:
    - asset: fonts/ProductSans-Bold-Italic.ttf
